ISSUE_TYPE_FILE = "FILE"
ISSUE_TYPE_SCHEMA = "SCHEMA"
ISSUE_TYPE_REFERENTIAL = "REFERENTIAL"
ISSUE_TYPE_ELIGIBILITY = "ELIGIBILITY"
ISSUE_TYPE_CLAIMS = "CLAIMS"
ISSUE_TYPE_ACCUMULATOR = "ACCUMULATOR"
ISSUE_TYPE_BUSINESS_RULE = "BUSINESS_RULE"

ISSUE_STATUS_OPEN = "OPEN"
ISSUE_STATUS_ACKNOWLEDGED = "ACKNOWLEDGED"
ISSUE_STATUS_RESOLVED = "RESOLVED"
ISSUE_STATUS_CLOSED = "CLOSED"

SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

# File processing statuses
FILE_STATUS_RECEIVED = "RECEIVED"
FILE_STATUS_VALIDATED = "VALIDATED"
FILE_STATUS_PROCESSED = "PROCESSED"
FILE_STATUS_FAILED = "FAILED"

# Processing run statuses
RUN_STATUS_RUNNING = "RUNNING"
RUN_STATUS_SUCCESS = "SUCCESS"
RUN_STATUS_PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
RUN_STATUS_FAILED = "FAILED"

# Status sets
FILE_PROCESSING_STATUSES = {
    "RECEIVED",
    "VALIDATED",
    "REJECTED",
    "PROCESSED",
    "FAILED",
}

ISSUE_SEVERITIES = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}

CASE_STATUSES = {
    "NEW",
    "IN_TRIAGE",
    "INVESTIGATING",
    "PENDING_VENDOR",
    "ESCALATED",
    "RESOLVED",
    "CLOSED",
}